Here i will attempt to write an encoder and a decoder for the hill cipher

In [116]:
from utils import *

In [117]:
# input two matrices of size n x m 
keyMat = [[12,7,3], 
          [4 ,5,6], 
          [7 ,8,9]] 
matrix2 = [[5],[8],[1]]
res = [[0 for y in range(len(matrix2[0]))] for x in range(len(keyMat))]  
# explicit for loops 
for i in range(len(keyMat)): 
    for j in range(len(matrix2[0])): 
        for k in range(len(matrix2)): 
  
            # resulted matrix 
            res[i][j] += keyMat[i][k] * matrix2[k][j] 
print (res) 

[[119], [66], [108]]


In [118]:
def multiply_matrices(keyMatrix,matrix2):
    if len(keyMatrix[0])!=len(matrix2):
        return('uh oh wrong size')
    res = [[0 for y in range(len(matrix2[0]))] for x in range(len(keyMatrix))]  
    for i in range(len(keyMatrix)): 
        for j in range(len(matrix2[0])): 
            for k in range(len(matrix2)): 
                # resulted matrix 
                res[i][j] += keyMatrix[i][k] * matrix2[k][j] 
    return(res) 


In [119]:
keyMat = [[12,7], 
          [4 ,5]]
matrix2 = [[1],[2]]
multiply_matrices(keyMat,matrix2)

[[26], [14]]

In [120]:
def convert_string_to_matrix(string, r):
    numList=text_to_num(string)
    c=int(len(numList)/r)
    res = [[0 for y in range(c)] for x in range(r)]  
    letter=0
    for i in range (len(res)):
        for j in range(len(res[0])):
            res[i][j]=numList[letter]
            letter+=1
    return res

In [121]:
convert_string_to_matrix('hi',2)
convert_string_to_matrix('threebyte',3)

[[19, 7, 17], [4, 4, 1], [24, 19, 4]]

In [129]:
def convert_matrix_to_string(matrix):
    s=''
    for r in range (len(matrix)):
        for c in range (len(matrix[0])):
            mod=matrix[r][c]%26
            l=chr(mod+97)
            s+=l
    return s

In [130]:
mat=[[1,2,3],[2,3,27]]
s=convert_matrix_to_string(mat)
print(s)

bcdcdb


In [134]:
def encode_hill(key,plaintext):
    r=int(math.sqrt(len(key)))
    encMatrix=convert_string_to_matrix(key,r)
    #add zs
    if len(plaintext)%r!=0:
        plaintext=plaintext+'z'*(r-(len(plaintext)%r))
    #every r letters
    i=0
    string=''
    while i<(len(plaintext)):
        plainMatrix=convert_string_to_matrix(plaintext[i: i+r: 1],r)
        i+=r
        cipherMatrix=multiply_matrices(encMatrix,plainMatrix)
        string+=convert_matrix_to_string(cipherMatrix)
    return string

In [135]:
encode_hill('fourtyone','hipster')

'fhcujvzmn'

In [136]:
encode_hill('four','hipster')

'rqpivgtl'

In [139]:
encode_hill('fourbyfourmatrix','hipster')

'zgoxgecw'

In [183]:
import numpy as np
keyMat = [[1,3], 
          [0,2]]
iden = [[1,0], 
        [0,1]]
mat=convert_string_to_matrix('threebyte',3)
det = int(np.linalg.det(keyMat))
inv = np.linalg.inv(keyMat)
aug=inv/det
print(det)
print(inv)
print (aug)
shouldbekey=np.dot(keyMat,inv)
print(shouldbekey)

2
[[ 1.  -1.5]
 [ 0.   0.5]]
[[ 0.5  -0.75]
 [ 0.    0.25]]
[[1. 0.]
 [0. 1.]]


In [189]:
def find_decryption_matrix(encMatrix):
    r=len(encMatrix)
    print(encMatrix)
    det = int(np.linalg.det(encMatrix))
    if det==3:
        det=9
    if det==9:
        det=3
    if det==5:
        det=21
    if det==21:
        det=5
    if det==17:
        det=23
    if det==23:
        det=17
    if det==11:
        det=19
    if det==19:
        det=11
    if det==15:
        det=7
    if det==7:
        det=15
    inv = np.linalg.inv(encMatrix)
    aug=inv/det
    modinv=det*aug
    return(modinv)
    

In [194]:
def decode_hill(encStr,ciphertext):
    r=int(math.sqrt(len(encStr)))
    encMat=convert_string_to_matrix(encStr,r)
    decMat=find_decryption_matrix(encMat)
    print(decMat)
    print('hi')
    decStr=convert_matrix_to_string(decMat)
    print(decStr)
    plain=encode_hill(decStr,ciphertext)
    return plain

In [195]:
keyMat="fortyfour"
plain="hipster"
cipher=encode_hill(keyMat,plain)
print(cipher)

mktimycit


In [196]:
plain=decode_hill(keyMat,cipher)
print(plain)

[[5, 14, 17], [19, 24, 5], [14, 20, 17]]
[[-0.24561404 -0.08133971  0.26953748]
 [ 0.20175439  0.12200957 -0.23763955]
 [-0.03508772 -0.07655502  0.11642743]]
hi


TypeError: integer argument expected, got float